Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/09/2023
Var
// Seção de Declarações das variáveis 
i: inteiro
numero:inteiro







Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número:")
leia(numero)


 para i de 1 ate 10 passo 1 faca
 
 escreval(numero, " x ", i, " = ", numero * i)
 fimpara




Fimalgoritmo